//! The naming system, stage 1: roots and sound rules.
//!
//! 1. The data loads and is well made: 300 to 400 roots, every area of
//!    meaning covered, every root a proper First Speech form.
//! 2. The canon comes back: every Roduro (Gogìḍu) word a root was worked
//!    backwards from is regenerated by the Roduro rules, or is listed as a
//!    deliberate exception.
//! 3. Each tongue keeps to its own sounds.
//! 4. Roots stay apart: no two share a word, except the few sound-alikes
//!    Qotiro's clipping makes.
//! 5. It is all a plain function: the same answers every time, and
//!    `docs/glossary.md` is exactly what the data says.
//!
//! Stage 2: putting words together, the sacred, and saying it.
//!
//! 6. The gods' canon names come back, and each wears down in every tongue.
//! 7. The peoples: the Roduro row is the canon four; all sixteen names differ.
//! 8. Compounds keep each tongue's shape, and Roduro's match the canon's.
//! 9. Every word can be said and spelled in plain letters, the game's font
//!    has every letter, and `docs/sacred.md` is what the data says.
//!
//! Stage 3: the names of things.
//!
//! 10. Everything the game names (jobs, goods, materials, crafts, items,
//!     made forms, town places, stations, base buildings, creatures,
//!     weather) has a native name.
//! 11. Every native name keeps its tongue's sounds, is short enough to
//!     say, and no two things share one; a thing made in one people's
//!     material is that people's; `docs/things.md` is what the data says.

use std::collections::{BTreeMap, HashSet};

use gahturiyu_sim::names::sound::{is_vowel, sounds};
use gahturiyu_sim::names::grammar::Order;
use gahturiyu_sim::names::{self, Affix, Field, Kind, Origin, Tongue};

fn all(t: Tongue) -> Vec<(String, String)> {
    names::roots().iter().map(|r| (r.id.clone(), names::word(&r.id, t).unwrap())).collect()
}

#[test]
fn the_root_list_is_well_made() {
    let roots = names::roots();
    assert!((300..=400).contains(&roots.len()), "{} roots; the brief asks for 300 to 400", roots.len());
    let mut ids = HashSet::new();
    for r in roots {
        assert!(ids.insert(&r.id), "two roots are called `{}`", r.id);
        assert!(names::well_formed(&r.first), "`{}` ({}) is not a First Speech form: syllables of one consonant and one vowel, the catch only between vowels", r.first, r.id);
        assert!(!r.gloss.is_empty());
        let n = sounds(&r.first).iter().filter(|c| is_vowel(**c)).count();
        assert!((1..=4).contains(&n), "`{}` has {n} syllables", r.first);
    }
    for f in [Field::Land, Field::Sea, Field::Sky, Field::Colour, Field::Plant, Field::Animal, Field::Material, Field::Craft, Field::Kin, Field::Quality, Field::Number, Field::Feeling, Field::Sacred] {
        let n = roots.iter().filter(|r| r.field == f).count();
        assert!(n >= 10, "only {n} roots for {f:?}");
    }
    // What the brief names outright.
    for id in [
        "rock", "stone", "hill", "slope", "cliff", "ledge", "crag", "mountain", "valley", "gorge", "cave", "shore", "sand", "bay", "cove", "reef", "island", "stack", "sea", "deep", "waterway", "spring", "marsh", "field", "forest", "heath", "road", "pass",
        "grow", "weave", "forge", "carve", "dive", "sail", "trade", "write", "guard", "heal", "teach", "mother", "father", "child", "line", "house", "hearth", "elder", "old", "new", "high", "low", "great", "small", "strong", "soft", "quiet", "bright", "first", "last",
        "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "hundred", "god", "rite", "omen", "death", "ancestor", "earth", "water", "fire", "air",
    ] {
        assert!(names::root(id).is_some(), "no root for `{id}`");
    }
    // The other files point at real roots.
    for x in names::irregulars() {
        assert!(names::root(&x.root).is_some() && !x.why.is_empty(), "irregular `{}`", x.root);
    }
    for l in names::loans() {
        assert!(names::root(&l.root).is_some() && l.into != l.from && !l.why.is_empty(), "loan `{}`", l.root);
        assert_eq!(names::origin(&l.root, l.into), Origin::Borrowed(l.from));
    }
    for id in names::COGNATE_SETS {
        assert!(names::root(id).is_some(), "cognate set `{id}`");
        assert!(Tongue::SPOKEN.iter().all(|t| names::origin(id, *t) == Origin::Inherited), "the cognate sets show inherited words only: `{id}`");
    }
}

#[test]
fn the_rules_regenerate_the_canon() {
    // Every root built on an existing Roduro word gives that word back.
    let mut from_canon = 0;
    for r in names::roots() {
        let Some(canon) = &r.canon else { continue };
        from_canon += 1;
        assert_eq!(&names::derive(&r.first, Tongue::Roduro), canon, "the Roduro rules turn `{}` ({}) into something other than the canon word", r.first, r.id);
        assert_eq!(&names::word(&r.id, Tongue::Roduro).unwrap(), canon);
    }
    assert!(from_canon >= 35, "only {from_canon} roots are worked back from canon words");
    // Every plain Gogìḍu word in the inventory is either a root's word or a
    // listed exception. (Grammar words, phrases and names are not roots.)
    let made: HashSet<String> = all(Tongue::Roduro).into_iter().map(|x| x.1).collect();
    for c in names::canon() {
        if c.kind == Kind::Word && c.tongue == Some(Tongue::Roduro) {
            assert!(made.contains(&c.word), "the canon word `{}` ({}) is not regenerated from any root", c.word, c.meaning);
        }
    }
    // The one exception so far, and it is on the record.
    assert_eq!(names::word("death", Tongue::Roduro).unwrap(), "ṭeyuʻoye");
    assert_eq!(names::origin("death", Tongue::Roduro), Origin::Irregular);
    // No new root lands on a canon word whose own meaning is not recorded.
    for w in ["qaya", "taḍoyì", "ṭahì", "hìtushi", "yi", "qo", "ro"] {
        assert!(!made.contains(w), "a root's Roduro word is `{w}`, which is a canon word already");
    }
    // The gods are built from words that exist.
    let words: HashSet<&str> = names::canon().iter().filter(|c| matches!(c.kind, Kind::Word | Kind::Grammar)).map(|c| c.word.as_str()).collect();
    for c in names::canon().iter().filter(|c| c.kind == Kind::God) {
        for p in &c.parts {
            assert!(words.contains(p.as_str()), "{} is built from `{p}`, which is not in the inventory", c.word);
        }
    }
}

/// Split a spelled word into its sounds and check each is allowed.
fn only(word: &str, allowed: &[&str], what: &str) {
    for c in sounds(word) {
        let s = match c {
            'θ' => "th".to_string(),
            'š' => "sh".to_string(),
            c => c.to_string(),
        };
        assert!(allowed.contains(&s.as_str()), "{what}: `{word}` has the sound `{s}`");
    }
}

/// The longest run of consonants in a word, and whether it ends in one.
fn shape(word: &str) -> (usize, bool) {
    let w = sounds(word);
    let (mut run, mut most) = (0, 0);
    for &c in &w {
        run = if is_vowel(c) { 0 } else { run + 1 };
        most = most.max(run);
    }
    (most, !is_vowel(*w.last().unwrap()))
}

#[test]
fn each_tongue_keeps_to_its_own_sounds() {
    const V: [&str; 6] = ["a", "e", "i", "ì", "o", "u"];
    for (id, w) in all(Tongue::Roduro) {
        // Open syllables; the deep consonants; no sounds of the lips or the nose.
        only(&w, &[&V[..], &["g", "d", "ḍ", "t", "ṭ", "q", "h", "r", "l", "th", "sh", "y", "ʻ"]].concat(), "Roduro");
        let (most, closed) = shape(&w);
        assert!(most <= 1 && !closed, "Roduro `{w}` ({id}) is not open syllables");
        assert!(!w.starts_with('ʻ'), "Roduro `{w}` starts with the catch");
    }
    for (id, w) in all(Tongue::Qotiro) {
        only(&w, &["a", "e", "i", "o", "u", "p", "t", "k", "q", "d", "g", "m", "n", "r", "x"], "Qotiro");
        let (most, closed) = shape(&w);
        assert!(most <= 2, "Qotiro `{w}` ({id}) piles up {most} consonants");
        let first = &names::root(&id).unwrap().first;
        let syllables = sounds(first).iter().filter(|c| is_vowel(**c)).count();
        // Words end hard. (A root of one syllable has nothing to lose.)
        assert!(closed || syllables == 1, "Qotiro `{w}` ({id}) trails off in a vowel");
    }
    for (id, w) in all(Tongue::Horaro) {
        // No hard stops, no q, no curled-back sounds, no hiss: liquids, nasals, w, h.
        only(&w, &["a", "e", "i", "o", "u", "l", "m", "n", "w", "r", "h"], "Horaro");
        let (most, closed) = shape(&w);
        assert!(most <= 1 && !closed, "Horaro `{w}` ({id}) is not open syllables");
    }
    for (id, w) in all(Tongue::Tadoro) {
        if matches!(names::origin(&id, Tongue::Tadoro), Origin::Borrowed(_)) {
            // A borrowed word is fitted to the same breathy consonants, but keeps a u where its lender had o.
            only(&w, &["a", "e", "i", "u", "h", "s", "sh", "th", "f", "w", "y"], "Ṭaḍoro (borrowed)");
        } else {
            only(&w, &["a", "e", "i", "u", "h", "s", "sh", "th", "f", "w", "y"], "Ṭaḍoro");
        }
        let (most, _) = shape(&w);
        assert!(most <= 1, "Ṭaḍoro `{w}` ({id}) has consonants together");
        // It may end on a breath, never on a glide.
        assert!(!w.ends_with('w') && !w.ends_with('y') && !w.ends_with('f'), "Ṭaḍoro `{w}` ends on a glide");
    }
    // Each tongue shows its signature somewhere, and often.
    let share = |t: Tongue, test: &dyn Fn(&str) -> bool| all(t).iter().filter(|x| test(&x.1)).count() as f32 / names::roots().len() as f32;
    assert!(share(Tongue::Roduro, &|w| w.contains('ḍ') || w.contains('ṭ') || w.contains('q') || w.contains('ʻ')) > 0.5);
    assert!(share(Tongue::Qotiro, &|w| shape(w).1) > 0.95);
    assert!(share(Tongue::Qotiro, &|w| shape(w).0 == 2) > 0.1, "Qotiro should have clusters");
    assert!(share(Tongue::Horaro, &|w| sounds(w).windows(2).any(|p| is_vowel(p[0]) && is_vowel(p[1]))) > 0.2, "Horaro should have vowels running together");
    assert!(share(Tongue::Tadoro, &|w| w.contains("au") || w.contains("ai") || w.contains("ei") || w.contains("ae")) > 0.15, "Ṭaḍoro should have diphthongs");
}

#[test]
fn roots_stay_apart() {
    for t in [Tongue::First, Tongue::Roduro, Tongue::Horaro, Tongue::Tadoro] {
        let mut seen: BTreeMap<String, String> = BTreeMap::new();
        for r in names::roots() {
            let w = if t == Tongue::First { r.first.clone() } else { names::word(&r.id, t).unwrap() };
            if let Some(other) = seen.insert(w.clone(), r.id.clone()) {
                panic!("{}: `{}` and `{}` are both `{w}`", t.name(), other, r.id);
            }
        }
    }
    // Qotiro wears words down hard, so it has some sound-alikes. Keep them few.
    let mut seen: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (id, w) in all(Tongue::Qotiro) {
        seen.entry(w).or_default().push(id);
    }
    let alike: Vec<_> = seen.iter().filter(|(_, v)| v.len() > 1).collect();
    assert!(alike.len() <= 18, "Qotiro has {} groups of sound-alike roots: {alike:?}", alike.len());
    assert!(alike.iter().all(|(_, v)| v.len() <= 3));
    // Nothing is worn down to a single sound, except the two grammar roots.
    for t in Tongue::SPOKEN {
        for (id, w) in all(t) {
            assert!(sounds(&w).len() >= 2, "{}: `{w}` ({id})", t.name());
        }
    }
}

#[test]
fn cognates_keep_their_correspondences() {
    // The same root in all four tongues, as the lore asks: grounded and open
    // in Earth, hard and closed in Fire, long and soft in Water, thin in Air.
    let say = |id: &str| Tongue::SPOKEN.map(|t| names::word(id, t).unwrap());
    assert_eq!(say("waterway"), ["hora", "por", "wora", "fausha"]);
    assert_eq!(say("earth"), ["rodu", "rod", "rolu", "shauthu"]);
    assert_eq!(say("wind"), ["ṭaḍo", "tron", "lano", "thaye"]);
    assert_eq!(say("night"), ["yaḍo", "dom", "iamo", "yawe"]);
    assert_eq!(say("spear"), ["qoti", "qot", "honi", "hausi"]);
    // The example names in languages.md are shapes these rules can make.
    assert_eq!(names::derive("qethuruka", Tongue::Qotiro), "qetruk");
    assert_eq!(names::derive("doruguna", Tongue::Qotiro), "dorgun");
    assert_eq!(names::derive("ketudu", Tongue::Tadoro), "hesuth");
    assert_eq!(names::derive("pemaʻi", Tongue::Tadoro), "fewai");
    assert_eq!(names::derive("moʻaṭanu", Tongue::Horaro), "moalanu");
    // A borrowed word starts from the lender's word, not from the root.
    assert_eq!(names::word("mountain", Tongue::Tadoro).unwrap(), names::borrow(&names::word("mountain", Tongue::Roduro).unwrap(), Tongue::Tadoro));
    assert_ne!(names::word("mountain", Tongue::Tadoro).unwrap(), names::derive(&names::root("mountain").unwrap().first, Tongue::Tadoro));
}

#[test]
fn it_is_all_a_plain_function() {
    for r in names::roots() {
        for t in Tongue::SPOKEN {
            assert_eq!(names::word(&r.id, t), names::word(&r.id, t));
        }
        assert_eq!(names::derive(&r.first, Tongue::First), r.first);
    }
    assert!(names::word("no such root", Tongue::Roduro).is_none());
    // The glossary in docs/ is what the data says.
    let written = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/glossary.md")).expect("docs/glossary.md");
    assert!(written == names::glossary(), "docs/glossary.md is out of date: run `cargo run --release --bin lang -- glossary > docs/glossary.md`");
}

// ---- Stage 2 ---------------------------------------------------------------------

/// A name or compound keeps to its tongue's sounds and shape.
fn fits(word: &str, t: Tongue, what: &str) {
    let w = word.to_lowercase();
    match t {
        Tongue::Roduro => {
            only(&w, &["a", "e", "i", "ì", "o", "u", "g", "d", "ḍ", "t", "ṭ", "q", "h", "r", "l", "th", "sh", "y", "ʻ"], what);
            let (most, closed) = shape(&w);
            assert!(most <= 1 && !closed && !w.starts_with('ʻ'), "{what}: Roduro `{w}` is not open syllables");
        }
        Tongue::Qotiro => {
            only(&w, &["a", "e", "i", "o", "u", "p", "t", "k", "q", "d", "g", "m", "n", "r", "x"], what);
            assert!(shape(&w).0 <= 3, "{what}: Qotiro `{w}` piles up consonants");
        }
        Tongue::Horaro => {
            only(&w, &["a", "e", "i", "o", "u", "l", "m", "n", "w", "r", "h"], what);
            let (most, closed) = shape(&w);
            assert!(most <= 1 && !closed, "{what}: Horaro `{w}` is not open syllables");
            let s = sounds(&w);
            assert!(!s.windows(4).any(|p| p.iter().all(|c| is_vowel(*c))), "{what}: Horaro `{w}` runs four vowels together");
        }
        Tongue::Tadoro => {
            only(&w, &["a", "e", "i", "u", "h", "s", "sh", "th", "f", "w", "y"], what);
            assert!(shape(&w).0 <= 1, "{what}: Ṭaḍoro `{w}` has consonants together");
        }
        Tongue::First => {}
    }
}

#[test]
fn the_gods_come_back_and_wear_down_in_every_tongue() {
    let s = names::sacred();
    // Every god in the inventory is here, under its canon name, and the other way round.
    let canon: HashSet<&str> = names::canon().iter().filter(|c| c.kind == Kind::God).map(|c| c.word.as_str()).collect();
    let here: HashSet<&str> = s.gods.iter().map(|g| g.canon.as_str()).collect();
    assert_eq!(canon, here, "the gods in sacred.ron and in canon.ron differ");
    assert_eq!(s.gods.len(), 20);
    let mut english = HashSet::new();
    for g in &s.gods {
        // The Roduro name is the canon one: by the rules, or as a listed exception.
        assert_eq!(g.name(Tongue::Roduro), g.canon, "{}", g.id);
        assert!(names::well_formed(&g.first), "{}: `{}` is not a First Speech form", g.id, g.first);
        if g.own.is_empty() {
            assert_eq!(names::capital(&names::derive(&g.first, Tongue::Roduro)), g.canon);
        }
        assert!(english.insert(&g.english) && !g.domain.is_empty());
        for r in &g.roots {
            assert!(names::root(r).is_some(), "{} is built on `{r}`, which is no root", g.id);
        }
        for p in &g.parents {
            assert!(names::god(p).is_some(), "{}'s parent `{p}`", g.id);
        }
        // Built on the roots it says: each root's First Speech form leaves its start in the name.
        let first = names::root(&g.roots[0]).unwrap().first.clone();
        let opening: String = first.chars().take(2).collect();
        assert!(g.first.starts_with(&opening) || g.roots[0] == "most", "{}: `{}` does not begin with `{first}`", g.id, g.first);
        for t in [Tongue::Qotiro, Tongue::Horaro, Tongue::Tadoro] {
            fits(&g.name(t), t, &g.id);
        }
    }
    // Children carry both parents.
    for g in s.gods.iter().filter(|g| !g.parents.is_empty()) {
        assert_eq!(g.parents.len(), 2);
    }
    // No two gods share a name in any tongue, and the Trinity's mark shows in every tongue.
    for t in Tongue::SPOKEN {
        let mut seen = HashSet::new();
        for g in &s.gods {
            assert!(seen.insert(g.name(t)), "{}: two gods are called {}", t.name(), g.name(t));
        }
        let mark = names::capital(&names::grammar(t).most.0);
        for id in ["hiqethoru", "hiyadote", "hitogia"] {
            assert!(names::god(id).unwrap().name(t).starts_with(&mark), "{}: {} lacks the mark of the highest", t.name(), id);
        }
    }
    // The same god, four ways.
    let g = names::god("horahida").unwrap();
    assert_eq!(Tongue::SPOKEN.map(|t| g.name(t)), ["Horahìda", "Porped", "Worawila", "Faushefith"]);
    // The elements and the sacred words exist in every tongue.
    assert_eq!(s.elements.len(), 4);
    for e in &s.elements {
        assert!(names::root(&e.root).is_some());
    }
    for term in &s.terms {
        for t in Tongue::SPOKEN {
            let w = names::make(&term.made, t).unwrap_or_else(|| panic!("`{}` names a root that does not exist", term.id));
            if term.id != "death" && term.id != "the_dead" {
                fits(&w, t, &term.id);
            }
        }
    }
}

#[test]
fn what_each_people_calls_each_people() {
    // The Roduro row is canon.
    assert_eq!(Tongue::SPOKEN.map(|of| names::people_name(of, Tongue::Roduro).unwrap()), ["Roduro", "Qotiro", "Horaro", "Ṭaḍoro"]);
    // What each calls itself.
    assert_eq!(names::people_name(Tongue::Qotiro, Tongue::Qotiro).unwrap(), "Trokroq");
    assert_eq!(names::people_name(Tongue::Horaro, Tongue::Horaro).unwrap(), "Roimawe");
    assert_eq!(names::people_name(Tongue::Tadoro, Tongue::Tadoro).unwrap(), "Sheisae");
    let mut seen = HashSet::new();
    for by in Tongue::SPOKEN {
        for of in Tongue::SPOKEN {
            let n = names::people_name(of, by).unwrap();
            fits(&n, by, "a people's name");
            assert!(seen.insert(n.clone()), "two peoples are called {n}");
            assert!(names::people_meaning(of, by).unwrap().ends_with("-kind"));
            // Each speaker's own mark for "a people" is on every name in its row.
            let (mark, _) = &names::grammar(by).kind;
            assert!(n.to_lowercase().contains(mark.as_str()), "{n} lacks {}'s mark `{mark}`", by.name());
        }
    }
    assert!(names::people_name(Tongue::First, Tongue::Roduro).is_none());
}

#[test]
fn compounds_keep_each_tongues_shape() {
    // Roduro's way of joining gives back the canon compounds it can.
    let r = Tongue::Roduro;
    assert_eq!(names::compound(r, "hora", "hohìda"), "horahìda");
    assert_eq!(names::compound(r, "guʻe", "redeqi"), "guʻedeqi");
    assert_eq!(names::compound(r, "guʻe", "hiqì"), "guʻehiqì");
    assert_eq!(names::compound(r, "qoti", "hiqì"), "qotihiqì");
    assert_eq!(names::compound(r, "lìdì", "hoya"), "lìdìhoya");
    assert_eq!(names::compound(r, "rìtha", "duya"), "rìthaduya");
    assert_eq!(names::compound(r, "hora", "ṭaḍo"), "horaṭaḍo");
    assert_eq!(names::with(r, "rodu", Affix::Kind), "roduro");
    assert_eq!(names::with(r, "qetho", Affix::Most), "hiqetho");
    // Two vowels never touch in Roduro: the catch goes between.
    assert_eq!(names::join(r, "guʻe", "ola"), "guʻeʻola");
    // Qotiro lets consonants meet, to a point.
    assert_eq!(names::join(Tongue::Qotiro, "qot", "roq"), "qotroq");
    assert_eq!(names::join(Tongue::Qotiro, "dort", "trom"), "dortrom");
    assert_eq!(names::join(Tongue::Qotiro, "xort", "kep"), "xortakep");
    assert_eq!(names::join(Tongue::Qotiro, "rod", "tok"), "rottok");
    // The Water tongues put the main word first.
    assert_eq!(names::grammar(Tongue::Horaro).order, Order::HeadFirst);
    assert_eq!(names::compound(Tongue::Horaro, "lano", "moa"), "moalano");
    // A syllable said twice over the join is said once.
    assert_eq!(names::compound(Tongue::Roduro, "ṭaḍo", "ḍoʻa"), "ṭaḍoʻa");
    assert_eq!(names::join(Tongue::Tadoro, "hesuth", "sae"), "hesuthesae");
    // Any two roots, any tongue: the compound still sounds like the tongue.
    let roots = names::roots();
    for t in Tongue::SPOKEN {
        let g = names::grammar(t);
        for (i, a) in roots.iter().enumerate().step_by(3) {
            let b = &roots[(i * 7 + 11) % roots.len()];
            let (wa, wb) = (names::word(&a.id, t).unwrap(), names::word(&b.id, t).unwrap());
            if matches!(a.id.as_str(), "death") || matches!(b.id.as_str(), "death") {
                continue;
            }
            let c = names::compound(t, &wa, &wb);
            fits(&c, t, &format!("{} + {}", a.id, b.id));
            let syllables = sounds(&c).iter().filter(|x| is_vowel(**x)).count();
            let first = sounds(if g.order == Order::HeadLast { &wa } else { &wb }).iter().filter(|x| is_vowel(**x)).count();
            assert!(syllables <= g.longest.max(first + 1) + 1, "{}: `{c}` ({} + {}) runs to {syllables} syllables", t.name(), a.id, b.id);
            for affix in [Affix::Kind, Affix::Agent, Affix::Place, Affix::Small, Affix::Great] {
                fits(&names::with(t, &wa, affix), t, &a.id);
            }
        }
    }
}

#[test]
fn every_word_can_be_said_and_spelled() {
    // The hints the lore itself gives.
    let r = Tongue::Roduro;
    assert_eq!(names::pronounce("Qotisho", r), "koh-TEE-shoh");
    assert_eq!(names::pronounce("Guʻehiqì", r), "goo-eh-HEE-kih");
    assert_eq!(names::pronounce("Shiḍuro", r), "shee-DOO-roh");
    assert_eq!(names::pronounce("Redeqiʻo", r), "reh-deh-KEE-oh");
    assert_eq!(names::pronounce("Hiqethoru", r), "hee-keh-THOH-roo");
    assert_eq!(names::pronounce("Ḍalìqa", r), "dah-LIH-kah");
    assert_eq!(names::pronounce("Dorgun", Tongue::Qotiro), "DOR-goon");
    assert_eq!(names::pronounce("Trokroq", Tongue::Qotiro), "TROK-rok");
    assert_eq!(names::pronounce("Moalanu", Tongue::Horaro), "moh-ah-LAH-noo");
    assert_eq!(names::pronounce("Hesuth", Tongue::Tadoro), "heh-SOOTH");
    assert_eq!(names::pronounce("gahì yi qo hotorì gayugo", r), "GAH-hih YEE KOH hoh-TOH-rih gah-YOO-goh");
    assert_eq!(names::ascii("Ṭaḍohi"), "Tadohi");
    assert_eq!(names::ascii("Guʻehiqì"), "Gu'ehiqi");
    assert_eq!(names::file_name("Guʻehiqì"), "guehiqi");

    // Every word there is.
    let mut all: Vec<(String, Tongue)> = Vec::new();
    for t in Tongue::SPOKEN {
        all.extend(names::roots().iter().map(|x| (names::word(&x.id, t).unwrap(), t)));
        all.extend(names::sacred().gods.iter().map(|g| (g.name(t), t)));
        all.extend(names::sacred().terms.iter().map(|x| (names::make(&x.made, t).unwrap(), t)));
        all.extend(Tongue::SPOKEN.iter().map(|of| (names::people_name(*of, t).unwrap(), t)));
    }
    let font = ab_glyph::FontRef::try_from_slice(include_bytes!("../assets/DejaVuSans.ttf")).expect("the game's font");
    for (w, t) in &all {
        let hint = names::pronounce(w, *t);
        assert!(!hint.is_empty() && hint.chars().all(|c| c.is_ascii_alphabetic() || c == '-'), "{}: `{w}` is said `{hint}`", t.name());
        let loud = hint.split('-').filter(|p| p.chars().all(|c| c.is_ascii_uppercase())).count();
        assert!(loud >= 1, "{}: `{w}` ({hint}) has no loud syllable", t.name());
        assert!(names::ascii(w).is_ascii(), "`{w}` has no plain-letter spelling");
        assert!(!names::file_name(w).is_empty());
        // The game can draw it, capital and all.
        for c in w.chars().chain(names::capital(w).chars()) {
            assert!(ab_glyph::Font::glyph_id(&font, c).0 != 0, "the game's font has no `{c}` (in `{w}`)");
        }
    }
    // Saying it is a plain function too.
    assert_eq!(names::pronounce("horahìda", r), names::pronounce("Horahìda", r));
    let written = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/sacred.md")).expect("docs/sacred.md");
    assert!(written == names::sacred::tables(), "docs/sacred.md is out of date: run `cargo run --release --bin lang -- sacred > docs/sacred.md`");
}

/// Every town place kind. (The match below stops compiling when one is added.)
fn place_kinds() -> Vec<gahturiyu_sim::sim::jobs::PlaceKind> {
    use gahturiyu_sim::sim::jobs::{PlaceKind as P, Shelf};
    let all = vec![
        P::Fields,
        P::Wilds,
        P::Woodlot,
        P::Dock,
        P::DivePlatform,
        P::KelpBeds,
        P::Boatyard,
        P::Kitchen,
        P::MessHall,
        P::Deck,
        P::Market,
        P::Shop(Shelf::Food),
        P::Shop(Shelf::Materials),
        P::Shop(Shelf::Goods),
        P::Inn,
        P::Shrine,
        P::GuardPost,
        P::Hall,
        P::HealingHouse,
        P::HealersHouse,
        P::TeachingHouse,
        P::ExchangeHouse,
        P::LettersHouse,
        P::TendersYard,
        P::Workyard,
        P::Forge,
        P::Bench,
        P::Desk,
        P::AlchemyTable,
        P::WeaversShed,
        P::Workshop,
        P::Quarry,
        P::CharcoalPit,
    ];
    for k in &all {
        match k {
            P::Fields | P::Wilds | P::Woodlot | P::Dock | P::DivePlatform | P::KelpBeds | P::Boatyard | P::Kitchen | P::MessHall | P::Deck | P::Market | P::Shop(_) | P::Inn | P::Shrine | P::GuardPost | P::Hall => {}
            P::HealingHouse | P::HealersHouse | P::TeachingHouse | P::ExchangeHouse | P::LettersHouse | P::TendersYard | P::Workyard | P::Forge | P::Bench | P::Desk | P::AlchemyTable | P::WeaversShed | P::Workshop | P::Quarry | P::CharcoalPit => {}
        }
    }
    all
}

#[test]
fn everything_the_game_names_has_a_native_name() {
    use gahturiyu_sim::sim::{animals, base, baselife, crafting, items, jobs, materials, weather};
    let mut named: Vec<(&str, String)> = Vec::new();
    named.extend(jobs::ALL_JOBS.iter().map(|j| ("job", j.name().to_string())));
    named.extend(baselife::JOBS.iter().map(|j| ("base job", j.name().to_string())));
    named.extend(jobs::GOODS.iter().map(|g| ("good", g.name().to_string())));
    named.extend(place_kinds().iter().map(|k| ("town place", k.name().to_string())));
    named.extend(materials::MATERIALS.iter().filter(|m| m.name != "Unmade").map(|m| ("material", m.name.to_string())));
    named.extend(materials::CRAFTS.iter().flat_map(|c| [("craft", c.name().to_string()), ("craft skill", c.skill().name().to_string())]));
    named.extend(crafting::STATIONS.iter().map(|s| ("station", s.name().to_string())));
    named.extend(base::BUILDINGS.iter().map(|b| ("base building", b.name.to_string())));
    named.extend(animals::SPECIES.iter().map(|s| ("creature", s.name.to_string())));
    named.extend(weather::Kind::ALL.iter().map(|k| ("weather", k.label().to_string())));
    named.extend(items::FORMS.iter().map(|f| ("made form", f.noun.to_string())));
    // A spell's notes, rite or scroll is named for the spell, and spells are
    // not named yet: only their head words are in the table.
    named.extend(items::ITEMS.iter().filter(|i| !matches!(i.kind, items::Kind::Notes(_) | items::Kind::Text(_) | items::Kind::Scroll(_))).map(|i| ("item", i.name.to_string())));
    for head in ["Notes", "Rite", "Scroll", "Manual"] {
        named.push(("book", head.to_string()));
    }
    assert!(named.len() > 300, "the game's own lists came up short: {}", named.len());
    let missing: Vec<String> = named.iter().filter(|(_, n)| names::thing(n).is_none()).map(|(what, n)| format!("{what} `{n}`")).collect();
    assert!(missing.is_empty(), "no entry in assets/lang/things.ron for: {}", missing.join(", "));
    for (_, n) in &named {
        for t in Tongue::SPOKEN {
            assert!(!names::native_name(n, t).unwrap().is_empty());
        }
    }

    // A made thing is the people's whose material it is usually made in.
    let tradition = |t: materials::Tradition| match t {
        materials::Tradition::Grown => Some(Tongue::Roduro),
        materials::Tradition::Fire => Some(Tongue::Qotiro),
        materials::Tradition::Sea => Some(Tongue::Horaro),
        materials::Tradition::Written => Some(Tongue::Tadoro),
        materials::Tradition::Shared => None,
    };
    for m in materials::MATERIALS.iter().filter(|m| m.name != "Unmade") {
        assert_eq!(names::thing(m.name).unwrap().belongs, tradition(m.tradition), "{} is {}", m.name, m.tradition.name());
    }
    // (By the item, not the bare noun: a "net" as a made form is the weighted net.)
    for f in items::FORMS {
        let item = items::ITEMS.iter().find(|i| i.key == f.key).unwrap_or_else(|| panic!("no item `{}`", f.key));
        assert_eq!(names::thing(item.name).unwrap().belongs, tradition(f.usual.def().tradition), "a {} is usually made in {}", item.name, f.usual.name());
    }
}

#[test]
fn the_names_of_things_hold_together() {
    for th in names::things() {
        th.check().unwrap_or_else(|e| panic!("things.ron, {}: {e}", th.english));
        assert!(!th.literal().is_empty(), "{} says nothing", th.english);
        for t in Tongue::SPOKEN {
            // Only the names that are shown: its own people's, or everyone's.
            if th.belongs.is_some() && th.belongs != Some(t) {
                continue;
            }
            let n = th.in_tongue(t);
            for w in n.split(' ') {
                fits(w, t, &th.english);
            }
            // Short enough to say: four beats a word (Horaro, all vowels, five).
            let most = if t == Tongue::Horaro { 5 } else { 4 };
            assert!(names::syllables(&n, t) <= most, "{}: {} `{n}` runs to {} beats", th.english, t.name(), names::syllables(&n, t));
            assert_eq!(th.native(t), (t, n.clone()));
            assert_eq!(names::native_name(&th.english, t).as_deref(), Some(n.as_str()));
            let hint = names::pronounce(&n, t);
            assert!(hint.chars().all(|c| c.is_ascii_alphabetic() || c == '-' || c == ' '), "{}: `{n}` is said `{hint}`", th.english);
        }
        // One people's thing is called the same whoever asks.
        if let Some(owner) = th.belongs {
            for t in Tongue::SPOKEN {
                assert_eq!(th.native(t), (owner, th.in_tongue(owner)));
            }
        }
    }
    // Nothing reads as a rude word in English: no root, no sacred word, no thing.
    assert_eq!(names::unfortunate("Kak"), Some("kak"));
    assert_eq!(names::unfortunate("Heshitha"), Some("shit"));
    assert_eq!(names::unfortunate("hiṭo yi goledoqo"), None);
    for t in Tongue::SPOKEN {
        let mut words: Vec<(String, String)> = names::roots().iter().map(|r| (r.id.clone(), names::word(&r.id, t).unwrap())).collect();
        words.extend(names::sacred().gods.iter().map(|g| (g.english.clone(), g.name(t))));
        words.extend(names::sacred().terms.iter().map(|x| ("a sacred word".to_string(), names::make(&x.made, t).unwrap())));
        // (A thing's name as it is shown: its own people's, or everyone's.)
        words.extend(names::things().iter().filter(|x| x.belongs.is_none() || x.belongs == Some(t)).map(|x| (x.english.clone(), x.in_tongue(t))));
        for (what, w) in &words {
            assert_eq!(names::unfortunate(w), None, "{}: `{w}` ({what}) reads badly in English", t.name());
        }
    }
    // No two things share a name in any tongue.
    for t in Tongue::SPOKEN {
        let alike = names::things::clashes(t);
        assert!(alike.is_empty(), "{}: these come out the same: {alike:?}", t.name());
    }
    // The canon holds: the revered beast keeps its name, the Overgrowth its god's.
    assert_eq!(names::native_name("Turiyu", Tongue::Roduro).as_deref(), Some("turiyu"));
    assert!(names::native_name("The Overgrowth", Tongue::Roduro).unwrap().ends_with("Qotihiqì"));
    assert_eq!(names::thing("stone tender").unwrap().english, "Stone Tender");
    assert_eq!(names::thing("Pearls").unwrap().english, "Pearl");
    assert!(names::thing("no such thing").is_none());
    assert_eq!(names::thing("Stone Tender").unwrap().literal(), "tend-er");
    assert_eq!(names::thing("Ink").unwrap().literal(), "black-water");
    assert_eq!(names::thing("Bronze ingot").unwrap().literal(), "board of gold-iron");

    let written = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/things.md")).expect("docs/things.md");
    assert!(written == names::things::tables(), "docs/things.md is out of date: run `cargo run --release --bin lang -- things > docs/things.md`");
}
