//! The naming system, stage 1: roots and sound rules.
//!
//! 1. The data loads and is well made: 300 to 400 roots, every area of
//!    meaning covered, every root a proper First Speech form.
//! 2. The canon comes back: every Roduro (Gogìḍu) word a root was worked
//!    backwards from is regenerated by the Roduro rules, or is listed as a
//!    deliberate exception.
//! 3. Each tongue keeps to its own sounds.
//! 4. Roots stay apart: no two share a word, except the few sound-alikes
//!    Qotiro's clipping makes.
//! 5. It is all a plain function: the same answers every time, and
//!    `docs/glossary.md` is exactly what the data says.

use std::collections::{BTreeMap, HashSet};

use gahturiyu_sim::names::sound::{is_vowel, sounds};
use gahturiyu_sim::names::{self, Field, Kind, Origin, Tongue};

fn all(t: Tongue) -> Vec<(String, String)> {
    names::roots().iter().map(|r| (r.id.clone(), names::word(&r.id, t).unwrap())).collect()
}

#[test]
fn the_root_list_is_well_made() {
    let roots = names::roots();
    assert!((300..=400).contains(&roots.len()), "{} roots; the brief asks for 300 to 400", roots.len());
    let mut ids = HashSet::new();
    for r in roots {
        assert!(ids.insert(&r.id), "two roots are called `{}`", r.id);
        assert!(names::well_formed(&r.first), "`{}` ({}) is not a First Speech form: syllables of one consonant and one vowel, the catch only between vowels", r.first, r.id);
        assert!(!r.gloss.is_empty());
        let n = sounds(&r.first).iter().filter(|c| is_vowel(**c)).count();
        assert!((1..=4).contains(&n), "`{}` has {n} syllables", r.first);
    }
    for f in [Field::Land, Field::Sea, Field::Sky, Field::Colour, Field::Plant, Field::Animal, Field::Material, Field::Craft, Field::Kin, Field::Quality, Field::Number, Field::Feeling, Field::Sacred] {
        let n = roots.iter().filter(|r| r.field == f).count();
        assert!(n >= 10, "only {n} roots for {f:?}");
    }
    // What the brief names outright.
    for id in [
        "rock", "stone", "hill", "slope", "cliff", "ledge", "crag", "mountain", "valley", "gorge", "cave", "shore", "sand", "bay", "cove", "reef", "island", "stack", "sea", "deep", "waterway", "spring", "marsh", "field", "forest", "heath", "road", "pass",
        "grow", "weave", "forge", "carve", "dive", "sail", "trade", "write", "guard", "heal", "teach", "mother", "father", "child", "line", "house", "hearth", "elder", "old", "new", "high", "low", "great", "small", "strong", "soft", "quiet", "bright", "first", "last",
        "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "hundred", "god", "rite", "omen", "death", "ancestor", "earth", "water", "fire", "air",
    ] {
        assert!(names::root(id).is_some(), "no root for `{id}`");
    }
    // The other files point at real roots.
    for x in names::irregulars() {
        assert!(names::root(&x.root).is_some() && !x.why.is_empty(), "irregular `{}`", x.root);
    }
    for l in names::loans() {
        assert!(names::root(&l.root).is_some() && l.into != l.from && !l.why.is_empty(), "loan `{}`", l.root);
        assert_eq!(names::origin(&l.root, l.into), Origin::Borrowed(l.from));
    }
    for id in names::COGNATE_SETS {
        assert!(names::root(id).is_some(), "cognate set `{id}`");
        assert!(Tongue::SPOKEN.iter().all(|t| names::origin(id, *t) == Origin::Inherited), "the cognate sets show inherited words only: `{id}`");
    }
}

#[test]
fn the_rules_regenerate_the_canon() {
    // Every root built on an existing Roduro word gives that word back.
    let mut from_canon = 0;
    for r in names::roots() {
        let Some(canon) = &r.canon else { continue };
        from_canon += 1;
        assert_eq!(&names::derive(&r.first, Tongue::Roduro), canon, "the Roduro rules turn `{}` ({}) into something other than the canon word", r.first, r.id);
        assert_eq!(&names::word(&r.id, Tongue::Roduro).unwrap(), canon);
    }
    assert!(from_canon >= 35, "only {from_canon} roots are worked back from canon words");
    // Every plain Gogìḍu word in the inventory is either a root's word or a
    // listed exception. (Grammar words, phrases and names are not roots.)
    let made: HashSet<String> = all(Tongue::Roduro).into_iter().map(|x| x.1).collect();
    for c in names::canon() {
        if c.kind == Kind::Word && c.tongue == Some(Tongue::Roduro) {
            assert!(made.contains(&c.word), "the canon word `{}` ({}) is not regenerated from any root", c.word, c.meaning);
        }
    }
    // The one exception so far, and it is on the record.
    assert_eq!(names::word("death", Tongue::Roduro).unwrap(), "ṭeyuʻoye");
    assert_eq!(names::origin("death", Tongue::Roduro), Origin::Irregular);
    // No new root lands on a canon word whose own meaning is not recorded.
    for w in ["qaya", "taḍoyì", "ṭahì", "hìtushi", "yi", "qo", "ro"] {
        assert!(!made.contains(w), "a root's Roduro word is `{w}`, which is a canon word already");
    }
    // The gods are built from words that exist.
    let words: HashSet<&str> = names::canon().iter().filter(|c| matches!(c.kind, Kind::Word | Kind::Grammar)).map(|c| c.word.as_str()).collect();
    for c in names::canon().iter().filter(|c| c.kind == Kind::God) {
        for p in &c.parts {
            assert!(words.contains(p.as_str()), "{} is built from `{p}`, which is not in the inventory", c.word);
        }
    }
}

/// Split a spelled word into its sounds and check each is allowed.
fn only(word: &str, allowed: &[&str], what: &str) {
    for c in sounds(word) {
        let s = match c {
            'θ' => "th".to_string(),
            'š' => "sh".to_string(),
            c => c.to_string(),
        };
        assert!(allowed.contains(&s.as_str()), "{what}: `{word}` has the sound `{s}`");
    }
}

/// The longest run of consonants in a word, and whether it ends in one.
fn shape(word: &str) -> (usize, bool) {
    let w = sounds(word);
    let (mut run, mut most) = (0, 0);
    for &c in &w {
        run = if is_vowel(c) { 0 } else { run + 1 };
        most = most.max(run);
    }
    (most, !is_vowel(*w.last().unwrap()))
}

#[test]
fn each_tongue_keeps_to_its_own_sounds() {
    const V: [&str; 6] = ["a", "e", "i", "ì", "o", "u"];
    for (id, w) in all(Tongue::Roduro) {
        // Open syllables; the deep consonants; no sounds of the lips or the nose.
        only(&w, &[&V[..], &["g", "d", "ḍ", "t", "ṭ", "q", "h", "r", "l", "th", "sh", "y", "ʻ"]].concat(), "Roduro");
        let (most, closed) = shape(&w);
        assert!(most <= 1 && !closed, "Roduro `{w}` ({id}) is not open syllables");
        assert!(!w.starts_with('ʻ'), "Roduro `{w}` starts with the catch");
    }
    for (id, w) in all(Tongue::Qotiro) {
        only(&w, &["a", "e", "i", "o", "u", "p", "t", "k", "q", "d", "g", "m", "n", "r", "x"], "Qotiro");
        let (most, closed) = shape(&w);
        assert!(most <= 2, "Qotiro `{w}` ({id}) piles up {most} consonants");
        let first = &names::root(&id).unwrap().first;
        let syllables = sounds(first).iter().filter(|c| is_vowel(**c)).count();
        // Words end hard. (A root of one syllable has nothing to lose.)
        assert!(closed || syllables == 1, "Qotiro `{w}` ({id}) trails off in a vowel");
    }
    for (id, w) in all(Tongue::Horaro) {
        // No hard stops, no q, no curled-back sounds, no hiss: liquids, nasals, w, h.
        only(&w, &["a", "e", "i", "o", "u", "l", "m", "n", "w", "r", "h"], "Horaro");
        let (most, closed) = shape(&w);
        assert!(most <= 1 && !closed, "Horaro `{w}` ({id}) is not open syllables");
    }
    for (id, w) in all(Tongue::Tadoro) {
        if matches!(names::origin(&id, Tongue::Tadoro), Origin::Borrowed(_)) {
            // A borrowed word is fitted to the same breathy consonants, but keeps a u where its lender had o.
            only(&w, &["a", "e", "i", "u", "h", "s", "sh", "th", "f", "w", "y"], "Ṭaḍoro (borrowed)");
        } else {
            only(&w, &["a", "e", "i", "u", "h", "s", "sh", "th", "f", "w", "y"], "Ṭaḍoro");
        }
        let (most, _) = shape(&w);
        assert!(most <= 1, "Ṭaḍoro `{w}` ({id}) has consonants together");
        // It may end on a breath, never on a glide.
        assert!(!w.ends_with('w') && !w.ends_with('y') && !w.ends_with('f'), "Ṭaḍoro `{w}` ends on a glide");
    }
    // Each tongue shows its signature somewhere, and often.
    let share = |t: Tongue, test: &dyn Fn(&str) -> bool| all(t).iter().filter(|x| test(&x.1)).count() as f32 / names::roots().len() as f32;
    assert!(share(Tongue::Roduro, &|w| w.contains('ḍ') || w.contains('ṭ') || w.contains('q') || w.contains('ʻ')) > 0.5);
    assert!(share(Tongue::Qotiro, &|w| shape(w).1) > 0.95);
    assert!(share(Tongue::Qotiro, &|w| shape(w).0 == 2) > 0.1, "Qotiro should have clusters");
    assert!(share(Tongue::Horaro, &|w| sounds(w).windows(2).any(|p| is_vowel(p[0]) && is_vowel(p[1]))) > 0.2, "Horaro should have vowels running together");
    assert!(share(Tongue::Tadoro, &|w| w.contains("au") || w.contains("ai") || w.contains("ei") || w.contains("ae")) > 0.15, "Ṭaḍoro should have diphthongs");
}

#[test]
fn roots_stay_apart() {
    for t in [Tongue::First, Tongue::Roduro, Tongue::Horaro, Tongue::Tadoro] {
        let mut seen: BTreeMap<String, String> = BTreeMap::new();
        for r in names::roots() {
            let w = if t == Tongue::First { r.first.clone() } else { names::word(&r.id, t).unwrap() };
            if let Some(other) = seen.insert(w.clone(), r.id.clone()) {
                panic!("{}: `{}` and `{}` are both `{w}`", t.name(), other, r.id);
            }
        }
    }
    // Qotiro wears words down hard, so it has some sound-alikes. Keep them few.
    let mut seen: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (id, w) in all(Tongue::Qotiro) {
        seen.entry(w).or_default().push(id);
    }
    let alike: Vec<_> = seen.iter().filter(|(_, v)| v.len() > 1).collect();
    assert!(alike.len() <= 18, "Qotiro has {} groups of sound-alike roots: {alike:?}", alike.len());
    assert!(alike.iter().all(|(_, v)| v.len() <= 3));
    // Nothing is worn down to a single sound, except the two grammar roots.
    for t in Tongue::SPOKEN {
        for (id, w) in all(t) {
            assert!(sounds(&w).len() >= 2, "{}: `{w}` ({id})", t.name());
        }
    }
}

#[test]
fn cognates_keep_their_correspondences() {
    // The same root in all four tongues, as the lore asks: grounded and open
    // in Earth, hard and closed in Fire, long and soft in Water, thin in Air.
    let say = |id: &str| Tongue::SPOKEN.map(|t| names::word(id, t).unwrap());
    assert_eq!(say("waterway"), ["hora", "por", "wora", "fausha"]);
    assert_eq!(say("earth"), ["rodu", "rod", "rolu", "shauthu"]);
    assert_eq!(say("wind"), ["ṭaḍo", "tron", "lano", "thaye"]);
    assert_eq!(say("night"), ["yaḍo", "dom", "iamo", "yawe"]);
    assert_eq!(say("spear"), ["qoti", "qot", "honi", "hausi"]);
    // The example names in languages.md are shapes these rules can make.
    assert_eq!(names::derive("qethuruka", Tongue::Qotiro), "qetruk");
    assert_eq!(names::derive("doruguna", Tongue::Qotiro), "dorgun");
    assert_eq!(names::derive("ketudu", Tongue::Tadoro), "hesuth");
    assert_eq!(names::derive("pemaʻi", Tongue::Tadoro), "fewai");
    assert_eq!(names::derive("moʻaṭanu", Tongue::Horaro), "moalanu");
    // A borrowed word starts from the lender's word, not from the root.
    assert_eq!(names::word("mountain", Tongue::Tadoro).unwrap(), names::borrow(&names::word("mountain", Tongue::Roduro).unwrap(), Tongue::Tadoro));
    assert_ne!(names::word("mountain", Tongue::Tadoro).unwrap(), names::derive(&names::root("mountain").unwrap().first, Tongue::Tadoro));
}

#[test]
fn it_is_all_a_plain_function() {
    for r in names::roots() {
        for t in Tongue::SPOKEN {
            assert_eq!(names::word(&r.id, t), names::word(&r.id, t));
        }
        assert_eq!(names::derive(&r.first, Tongue::First), r.first);
    }
    assert!(names::word("no such root", Tongue::Roduro).is_none());
    // The glossary in docs/ is what the data says.
    let written = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/glossary.md")).expect("docs/glossary.md");
    assert!(written == names::glossary(), "docs/glossary.md is out of date: run `cargo run --release --bin lang -- glossary > docs/glossary.md`");
}
